name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * 0" #once a week 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3


      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN }}     
          user: KeanuDecleene
          template: classic
          filename: github-metrics.svg
          config_timezone: Pacific/Auckland
          output_action: commit                   
          committer_token: ${{ secrets.METRIC_TOKEN }}
          committer_branch: main
          committer_message: "Update GitHub Metrics"
